// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dsc.hikomaki.domain;

import com.dsc.hikomaki.domain.Prato;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Prato_Roo_Configurable {
    
    declare @type: Prato: @Configurable;
    
}
