// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dsc.hikomaki.domain;

import com.dsc.hikomaki.domain.Funcionario;
import com.dsc.hikomaki.domain.FuncionarioDataOnDemand;
import com.dsc.hikomaki.servico.FuncionarioService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FuncionarioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FuncionarioDataOnDemand: @Component;
    
    private Random FuncionarioDataOnDemand.rnd = new SecureRandom();
    
    private List<Funcionario> FuncionarioDataOnDemand.data;
    
    @Autowired
    FuncionarioService FuncionarioDataOnDemand.funcionarioService;
    
    public Funcionario FuncionarioDataOnDemand.getNewTransientFuncionario(int index) {
        Funcionario obj = new Funcionario();
        setDataNasc(obj, index);
        setNome(obj, index);
        setTelefone(obj, index);
        setTurno(obj, index);
        return obj;
    }
    
    public void FuncionarioDataOnDemand.setDataNasc(Funcionario obj, int index) {
        Date dataNasc = new Date(new Date().getTime() - 10000000L);
        obj.setDataNasc(dataNasc);
    }
    
    public void FuncionarioDataOnDemand.setNome(Funcionario obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void FuncionarioDataOnDemand.setTelefone(Funcionario obj, int index) {
        String telefone = "telefone_" + index;
        obj.setTelefone(telefone);
    }
    
    public void FuncionarioDataOnDemand.setTurno(Funcionario obj, int index) {
        String turno = "turno_" + index;
        obj.setTurno(turno);
    }
    
    public Funcionario FuncionarioDataOnDemand.getSpecificFuncionario(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Funcionario obj = data.get(index);
        Long id = obj.getId();
        return funcionarioService.findFuncionario(id);
    }
    
    public Funcionario FuncionarioDataOnDemand.getRandomFuncionario() {
        init();
        Funcionario obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return funcionarioService.findFuncionario(id);
    }
    
    public boolean FuncionarioDataOnDemand.modifyFuncionario(Funcionario obj) {
        return false;
    }
    
    public void FuncionarioDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = funcionarioService.findFuncionarioEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Funcionario' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Funcionario>();
        for (int i = 0; i < 10; i++) {
            Funcionario obj = getNewTransientFuncionario(i);
            try {
                funcionarioService.saveFuncionario(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
