// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dsc.hikomaki.domain;

import com.dsc.hikomaki.domain.Funcionario;
import com.dsc.hikomaki.domain.FuncionarioDataOnDemand;
import com.dsc.hikomaki.domain.FuncionarioIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FuncionarioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FuncionarioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FuncionarioIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FuncionarioIntegrationTest: @Transactional;
    
    @Autowired
    FuncionarioDataOnDemand FuncionarioIntegrationTest.dod;
    
    @Test
    public void FuncionarioIntegrationTest.testCountFuncionarios() {
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", dod.getRandomFuncionario());
        long count = Funcionario.countFuncionarios();
        Assert.assertTrue("Counter for 'Funcionario' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FuncionarioIntegrationTest.testFindFuncionario() {
        Funcionario obj = dod.getRandomFuncionario();
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to provide an identifier", id);
        obj = Funcionario.findFuncionario(id);
        Assert.assertNotNull("Find method for 'Funcionario' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Funcionario' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FuncionarioIntegrationTest.testFindAllFuncionarios() {
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", dod.getRandomFuncionario());
        long count = Funcionario.countFuncionarios();
        Assert.assertTrue("Too expensive to perform a find all test for 'Funcionario', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Funcionario> result = Funcionario.findAllFuncionarios();
        Assert.assertNotNull("Find all method for 'Funcionario' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Funcionario' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FuncionarioIntegrationTest.testFindFuncionarioEntries() {
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", dod.getRandomFuncionario());
        long count = Funcionario.countFuncionarios();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Funcionario> result = Funcionario.findFuncionarioEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Funcionario' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Funcionario' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FuncionarioIntegrationTest.testFlush() {
        Funcionario obj = dod.getRandomFuncionario();
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to provide an identifier", id);
        obj = Funcionario.findFuncionario(id);
        Assert.assertNotNull("Find method for 'Funcionario' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFuncionario(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Funcionario' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FuncionarioIntegrationTest.testMergeUpdate() {
        Funcionario obj = dod.getRandomFuncionario();
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to provide an identifier", id);
        obj = Funcionario.findFuncionario(id);
        boolean modified =  dod.modifyFuncionario(obj);
        Integer currentVersion = obj.getVersion();
        Funcionario merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Funcionario' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FuncionarioIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", dod.getRandomFuncionario());
        Funcionario obj = dod.getNewTransientFuncionario(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Funcionario' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Funcionario' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FuncionarioIntegrationTest.testRemove() {
        Funcionario obj = dod.getRandomFuncionario();
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Funcionario' failed to provide an identifier", id);
        obj = Funcionario.findFuncionario(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Funcionario' with identifier '" + id + "'", Funcionario.findFuncionario(id));
    }
    
}
