// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dsc.hikomaki.domain;

import com.dsc.hikomaki.domain.Mesa;
import com.dsc.hikomaki.domain.MesaDataOnDemand;
import com.dsc.hikomaki.domain.MesaIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MesaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MesaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MesaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MesaIntegrationTest: @Transactional;
    
    @Autowired
    MesaDataOnDemand MesaIntegrationTest.dod;
    
    @Test
    public void MesaIntegrationTest.testCountMesas() {
        Assert.assertNotNull("Data on demand for 'Mesa' failed to initialize correctly", dod.getRandomMesa());
        long count = Mesa.countMesas();
        Assert.assertTrue("Counter for 'Mesa' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MesaIntegrationTest.testFindMesa() {
        Mesa obj = dod.getRandomMesa();
        Assert.assertNotNull("Data on demand for 'Mesa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mesa' failed to provide an identifier", id);
        obj = Mesa.findMesa(id);
        Assert.assertNotNull("Find method for 'Mesa' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Mesa' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MesaIntegrationTest.testFindAllMesas() {
        Assert.assertNotNull("Data on demand for 'Mesa' failed to initialize correctly", dod.getRandomMesa());
        long count = Mesa.countMesas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Mesa', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Mesa> result = Mesa.findAllMesas();
        Assert.assertNotNull("Find all method for 'Mesa' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Mesa' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MesaIntegrationTest.testFindMesaEntries() {
        Assert.assertNotNull("Data on demand for 'Mesa' failed to initialize correctly", dod.getRandomMesa());
        long count = Mesa.countMesas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Mesa> result = Mesa.findMesaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Mesa' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Mesa' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MesaIntegrationTest.testFlush() {
        Mesa obj = dod.getRandomMesa();
        Assert.assertNotNull("Data on demand for 'Mesa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mesa' failed to provide an identifier", id);
        obj = Mesa.findMesa(id);
        Assert.assertNotNull("Find method for 'Mesa' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMesa(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Mesa' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MesaIntegrationTest.testMergeUpdate() {
        Mesa obj = dod.getRandomMesa();
        Assert.assertNotNull("Data on demand for 'Mesa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mesa' failed to provide an identifier", id);
        obj = Mesa.findMesa(id);
        boolean modified =  dod.modifyMesa(obj);
        Integer currentVersion = obj.getVersion();
        Mesa merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Mesa' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MesaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Mesa' failed to initialize correctly", dod.getRandomMesa());
        Mesa obj = dod.getNewTransientMesa(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Mesa' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Mesa' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Mesa' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MesaIntegrationTest.testRemove() {
        Mesa obj = dod.getRandomMesa();
        Assert.assertNotNull("Data on demand for 'Mesa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mesa' failed to provide an identifier", id);
        obj = Mesa.findMesa(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Mesa' with identifier '" + id + "'", Mesa.findMesa(id));
    }
    
}
