// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dsc.hikomaki.domain;

import com.dsc.hikomaki.domain.Prato;
import com.dsc.hikomaki.domain.PratoDataOnDemand;
import com.dsc.hikomaki.domain.PratoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PratoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PratoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PratoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PratoIntegrationTest: @Transactional;
    
    @Autowired
    PratoDataOnDemand PratoIntegrationTest.dod;
    
    @Test
    public void PratoIntegrationTest.testCountPratoes() {
        Assert.assertNotNull("Data on demand for 'Prato' failed to initialize correctly", dod.getRandomPrato());
        long count = Prato.countPratoes();
        Assert.assertTrue("Counter for 'Prato' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PratoIntegrationTest.testFindPrato() {
        Prato obj = dod.getRandomPrato();
        Assert.assertNotNull("Data on demand for 'Prato' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prato' failed to provide an identifier", id);
        obj = Prato.findPrato(id);
        Assert.assertNotNull("Find method for 'Prato' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Prato' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PratoIntegrationTest.testFindAllPratoes() {
        Assert.assertNotNull("Data on demand for 'Prato' failed to initialize correctly", dod.getRandomPrato());
        long count = Prato.countPratoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Prato', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Prato> result = Prato.findAllPratoes();
        Assert.assertNotNull("Find all method for 'Prato' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Prato' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PratoIntegrationTest.testFindPratoEntries() {
        Assert.assertNotNull("Data on demand for 'Prato' failed to initialize correctly", dod.getRandomPrato());
        long count = Prato.countPratoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Prato> result = Prato.findPratoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Prato' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Prato' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PratoIntegrationTest.testFlush() {
        Prato obj = dod.getRandomPrato();
        Assert.assertNotNull("Data on demand for 'Prato' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prato' failed to provide an identifier", id);
        obj = Prato.findPrato(id);
        Assert.assertNotNull("Find method for 'Prato' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPrato(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Prato' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PratoIntegrationTest.testMergeUpdate() {
        Prato obj = dod.getRandomPrato();
        Assert.assertNotNull("Data on demand for 'Prato' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prato' failed to provide an identifier", id);
        obj = Prato.findPrato(id);
        boolean modified =  dod.modifyPrato(obj);
        Integer currentVersion = obj.getVersion();
        Prato merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Prato' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PratoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Prato' failed to initialize correctly", dod.getRandomPrato());
        Prato obj = dod.getNewTransientPrato(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Prato' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Prato' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Prato' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PratoIntegrationTest.testRemove() {
        Prato obj = dod.getRandomPrato();
        Assert.assertNotNull("Data on demand for 'Prato' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prato' failed to provide an identifier", id);
        obj = Prato.findPrato(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Prato' with identifier '" + id + "'", Prato.findPrato(id));
    }
    
}
